version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - /^release.*/
                - master
                - feature/test-ci
            # tags:
            #   only: /^v.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            # tags:
            #   only: /^v.*/
      - deploy-test:
          requires:
            - build
          filters:
            branches:
              only:
                feature/test-ci
            # tags:
            #   only: /^v.*/

jobs:
  build:
    docker:
      - image: nikolaik/python-nodejs:python3.7-nodejs12-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-module-{{ checksum "mowecl_react/yarn.lock" }}
      - run:
          name: Install npm dependencies
          command: |
              cd mowecl_react
              yarn install
      - run:
          name: Build code
          command: |
              cd mowecl_react
              CI=false yarn build
      # - run:
      #     name: Install python dependencies
      #     command: pip install -e .
      - run:
          name: explore
          command: |
              ls -l
              ls -l mowecl_react
              ls -l mopidy_mowecl
              cd mowecl_react
              pwd
              ls -l
      - save_cache:
          paths:
            - mowecl_react/node_modules
          key: node-module-{{ checksum "mowecl_react/yarn.lock" }}
      - save_cache:
          paths:
            - mowecl_react/build
          key: build-cache-{{ .BuildNum  }}
  deploy:
    docker:
      - image: nikolaik/python-nodejs:python3.7-nodejs12-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .BuildNum  }}
      - run:
          name: Prepare .pypirc
          command: |
            echo -e "[distutils]\nindex-servers =\n pypi" >> ~/.pypirc
            echo -e "[pypi]\nusername = sapristi\npassword = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: Create and distribute package to pypi
          command: python setup.py sdist upload -r pypi
  deploy-test:
    docker:
      - image: nikolaik/python-nodejs:python3.7-nodejs12-stretch
    steps:
      - checkout
      - restore_cache:
          keys: [cache-$CIRCLE_SHA1]
      - run:
          name: Prepare .pypirc
          command: |
            echo -e "[distutils]\nindex-servers =\n testpypi" >> ~/.pypirc
            echo -e "[testpypi]\nrepository: https://test.pypi.org/legacy/ " >> ~/.pypirc
            echo -e "username: sapristi\npassword: $PYPI_TEST_PASSWORD" >> ~/.pypirc
      - run:
          name: Create and distribute package to test.pypi
          command: python setup.py bdist_wheel upload -r testpypi
