version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
            branches:
              ignore: /.*/

            #   only:
            #     - /^release.*/
            #     - master
            # tags:
            #   only: /^v.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            # tags:
            #   only: /^v.*/
jobs:
  build:
    docker:
      - image: nikolaik/python-nodejs:python3.7-nodejs12-stretch
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
              cd mowecl_react
              yarn install
      - run:
          name: Build code
          command: |
              cd mowecl_react
              CI=false yarn build
      - run:
          name: Install python dependencies
          command: pip install -e .
      - save_cache:
          paths:
            - mowecl_react/build
          key: cache-$CIRCLE_SHA1
  deploy:
    docker:
      - image: nikolaik/python-nodejs:python3.7-nodejs12-stretch
    steps:
      - checkout
      - restore_cache:
          keys: [cache-$CIRCLE_SHA1]
      - run:
          name: Prepare .pypirc
          command: |
            echo -e "[distutils]\nindex-servers =\n pypi" >> ~/.pypirc
            echo -e "[pypi]\nusername = sapristi\npassword = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: Create and distribute package to pypi
          command: python setup.py sdist upload -r pypi
